server:
  port: ${DISPATCHER_PORT}
  ssl:
    enabled: false

bot:
  name: ${TG_BOT_NAME}
  token: ${TG_BOT_TOKEN}
  uri: ${TG_BOT_URI}

spring:
  rabbitmq:
    host: ${RABBIT_HOST}
    port: ${RABBIT_PORT}
    username: ${RABBIT_USERNAME}
    password: ${RABBIT_PASSWORD}
    queues:
      text-message-update: ${RABBIT_TEXT_MESSAGE_UPDATE_QUEUE}
      doc-message-update: ${RABBIT_DOC_MESSAGE_UPDATE_QUEUE}
      photo-message-update: ${RABBIT_PHOTO_MESSAGE_UPDATE_QUEUE}
      answer-message: ${RABBIT_ANSWER_MESSAGE_QUEUE}
