server:
  port: ${NODE_PORT}

spring:
  rabbitmq:
    host: ${RABBIT_HOST}
    port: ${RABBIT_PORT}
    username: ${RABBIT_USERNAME}
    password: ${RABBIT_PASSWORD}
    queues:
      text-message-update: ${RABBIT_TEXT_MESSAGE_UPDATE_QUEUE}
      doc-message-update: ${RABBIT_DOC_MESSAGE_UPDATE_QUEUE}
      photo-message-update: ${RABBIT_PHOTO_MESSAGE_UPDATE_QUEUE}
      answer-message: ${RABBIT_ANSWER_MESSAGE_QUEUE}
      registration-mail: ${RABBIT_REGISTRATION_MAIL_QUEUE}

  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

token: ${TG_BOT_TOKEN}

service:
  file_info:
    uri: ${TG_BOT_FILE_INFO_URI}
  file_storage:
    uri: ${TG_BOT_FILE_STORAGE_URI}
  mail:
    uri: http://127.0.0.1:${MAIL_SERVICE_PORT}/mail/send

link:
  address: ${HOST_URL}:${REST_SERVICE_PORT}

salt: ${SALT}
