server:
  port: ${MAIL_SERVICE_PORT}

spring:
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    protocol: ${MAIL_PROTOCOL}
    username: ${MAIL_USERNAME_IDEA}
    password: ${MAIL_PASSWORD_IDEA}
  rabbitmq:
    host: ${RABBIT_HOST}
    port: ${RABBIT_PORT}
    username: ${RABBIT_USERNAME}
    password: ${RABBIT_PASSWORD}
    queues:
      registration-mail: ${RABBIT_REGISTRATION_MAIL_QUEUE}

service:
  activation:
    uri: ${ACTIVATION_URI}
